### ISSUE TITLE
Option to enable move constructors

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/podio#202]
Can an option be created to enable the move  constructors which are implicitly deleted?
https://en.cppreference.com/w/cpp/language/move_constructor

At the top of the yaml file something like
```
defaultMoveConstructors: true
defaultCopyConstructors: false
```

**Comment by tmadlener** [comment]
Hi @whit2333,

I suppose you would want move constructors for the object classes and not for the collections? Is there a specific use case you have in mind for the move constructor?

Assuming you mean move constructors for the object classes, I am not sure we really gain anything from them because the object classes are really just handles to the resources and all we do when copying such a class is copying the pointer to the actual resource (and increment a reference counter). But maybe I am missing something here.

Considering the following definition
```yaml
Example:
  Members:
    - int i
```

podio will generate the following classes ([see here](https://godbolt.org/z/PGT8zqGdf) for a more complete implementation)
```cpp
struct ExampleData {
  int i{};
};

struct ExampleObj : podio::ObjBase {
  // ... some constructors that initialize the podio::ObjBase as desired
  ExampleData data;
};

// This is the "user-facing" object class
class Example {
public:
  Example() : m_obj(new ExampleObj()) {}

  Example(const Example& other) : m_obj(other.m_obj) {
    m_obj->acquire();
  }
  // similar version of an assignment operator

  ~Example() {
    if (m_obj) m_obj->release();
  }
private:
  ExampleObj* m_obj;
};
```

The [`podio::ObjBase`](https://github.com/AIDASoft/podio/blob/master/include/podio/ObjBase.h) is basically a reference counter that also takes into account whether an object is part of a collection or not.

So in the current version all that a copy constructor does is to get the `Obj` pointer and call `acquire` on that. What a move constructor/assignment operator could do in this case is to omit the call to `acquire` and set `other.m_obj = nullptr` to leave the moved-from object in a valid but essentially undefined (and in this case unusable) state.

**Comment by whit2333** [comment]
Hi @tmadlener ,

Our use case is simple: we want to use Gaudi's new(ish) functional algorithms.

Whit

**Comment by hegner** [comment]
Hi @whit2333 !

Will add that. Is there any particular time scale you have in mind / need?
  
Benedikt

**Comment by tmadlener** [comment]
Hi @whit2333,

took us a bit but we have #252 now which would make collections movable. Is that enough for your use case, or did you have more in mind?

Thomas

**Comment by tmadlener** [comment]
Closing this, since I think the main issue is solved. Feel free to open gain, in case I am wrong.
