### ISSUE TITLE
Lost compatibility with Python2

### ISSUE THREAD

**Issue by hegner** [AIDASoft/podio#207]
It seems PODIO lost its compatibility with Python2 by introducing formatted strings in e.g. https://github.com/AIDASoft/podio/blob/eb298b1c0e935c8ba18a8c5726328846ccfbaa89/python/generator_utils.py#L120

Are we ready to give up on Python2 compatibility?

At the same time, the handling of Python2 vs Python3 is not really stable for systems, where Python 3 is explicitly called _python3_. And Python2 just called _python_, Throughout the CMake macros we just talk about _python_

**Comment by tmadlener** [comment]
I thought we had decided that at one of the meetings after #182 was merged, because with that we removed the last CI workflows that were still using python2. At least I stopped worrying about python2 compatibility after that, and also some of the things that are in #143 would break, e.g.
https://github.com/AIDASoft/podio/pull/143/files#diff-4dd2bca85ef3468fc6ba4f2701bc3131d54a47d333c9fa2112e85dddd5de988cR64

**Comment by andresailer** [comment]
Noted here: https://codimd.web.cern.ch/lkFym47kSdKGWqmPLCpf-w#Podio7 python3 only

**Comment by hegner** [comment]
thanks. Seems I forgot about that. I will update some of the docs

**Comment by hegner** [comment]
#209
