### ISSUE TITLE
Out of bounds access on `prepareForWrite()`

### ISSUE THREAD

**Issue by fdplacido** [AIDASoft/podio#241]
On trying to write some collection, `prepareForWrite()` may try to access an index out of bounds.

As an example I will take `ParticleIDCollectionData.cc` from EMD4hep. The relevant part is generated by these two templates:
- https://github.com/AIDASoft/podio/blob/master/python/templates/CollectionData.cc.jinja2#L117
- https://github.com/AIDASoft/podio/blob/master/python/templates/macros/collections.jinja2#L39

And here would be the generated code:

```cpp
void ParticleIDCollectionData::prepareForWrite(bool isSubsetColl) {
  for (auto& pointer : m_refCollections) { pointer->clear(); }

  // If this is a subset collection use the relation storing mechanism to
  // store the ObjectIDs of all referenced objects and nothing else
  if (isSubsetColl) {
    for (const auto* obj : entries) {
      m_refCollections[0]->emplace_back(obj->id);
    }
    return;
  }

  // Normal collections have to store the data and all the relations
  m_data->reserve(entries.size());
  for (auto& obj : entries) { m_data->push_back(obj->data); }

const auto parameters_size = std::accumulate(entries.begin(), entries.end(), 0,
  [](size_t sum, const ParticleIDObj* obj) { return sum + obj->m_parameters->size(); });
  m_vec_parameters->reserve(parameters_size);
  int parameters_index = 0;
  for (size_t i = 0, size = m_data->size(); i != size; ++i) {
    (*m_data)[i].parameters_begin = parameters_index;
    (*m_data)[i].parameters_end += parameters_index;
    parameters_index = (*m_data)[i].parameters_end;
    for (const auto& it : (*m_vecs_parameters[i])) { m_vec_parameters->push_back(it); }

  }
}
```

The last part will loop over `m_data->size()`, but in an inner for loop will try to access `*m_vecs_parameters[i]` using the index based on `m_data->size()`. If the sizes are different this results in the out of bounds access. 
In my example, `m_data` has size 8, `m_vecs_parameters` has size 4, `entries` has size 4, and trying to access `*m_vecs_parameters[4]` crashes. 

---

Temporary solution is to `m_data->clear();` before the `m_data->reserve(entries.size());`

**Comment by tmadlener** [comment]
I think the underlying problem in this case is that `prepareForWrite` is called twice on the same collection, which is not foreseen to happen at the moment. I am not even sure it should be something that we support, other than silently ignoring subsequent calls if a collection has already been prepared. We do this e.g. on the reading side, where we mark a collection as being read from a file, so that calls to `prepareForWrite` are basically no-ops.

What happens in the case described above is that during the first call everything works as expected:
- Reserve the number of elements in the `m_data`, and relation handling vectors
- Loop over all the elements in the collection and
  - store the begin and end indices for vector members and multi relations into the data POD
  - copy the data POD into `m_data`
  - put the values of all individual vector members into one large `m_vecs_{{ member.name }}` vector, which will be written to file

On a second call this happens again, only that now the data PODs are in the `m_data` vector a second time making the size of `m_data` twice as big as it should be, which results in the out of bounds access in the handling of the vector members.

So, I think what should happen (at the collection) level is to track whether a collection has been prepared (or read) already and simply make this call a no-op.
