### ISSUE TITLE
EventStore + ROOTReader ownership of CollectionIDTable

### ISSUE THREAD

**Issue by faustus123** [AIDASoft/podio#314]
- OS version: all
 - Compiler version: all
 - PODIO version: v00-14-01
 
This took me quite a while to figure out.

What I am trying to do is read events into multiple EventStore objects using the same ROOTReader. The reads are being done sequentially. The idea is once an event is read in, I can pass the EventStore into one thread and then I read another event into a different EventStore object for a different thread. This, however gives seg. faults. The issue (or at least the main one right now) is the following:

In ROOTReader::OpenFiles a _CollectionIDTable_ is instantiated and the _ROOTReader_ object keeps a pointer to it.

When EventStore::setReader is called, it gets that pointer and places it in a unique_ptr. This essentially gives ownership to the EventStore even though ROOTReader still has a pointer that it uses.

Deleting the EventStore object will free the CollectionIDTable leaving the ROOTReader with an invalid pointer. Calling EventStore::setReader using a new event store will cause a second unique_ptr to exist to the CollectionIDTable created by ROOTReader. 

Without knowing all of the details, I can't say what the best fix is. I would guess either using shared_ptr everywhere, or just make the EventStore use a raw pointer rather than unique_ptr.

Oh, and one other suggestion. If ROOTReader placed things in protected: sections rather than private: I would be able to handle this sort of thing in my code. I know it is not really good programming form, but would give me a way to tweak things to figure it out and keep rolling for the moment until an official fix came out. Again, just a thought.

**Comment by tmadlener** [comment]
The main issue is a recurring one: The `EventStore` that is shipped with podio was really only meant as an example implementation of how one could achieve the functionality and it has since unfortunately long outlived its original scope. We try to rectify this (and other things) with the `Frame` approach, where each `Frame` can stand on its own and different `Frame`s can easily be put onto different threads.

For this we have a prototype implementation in #287. This is essentially ready for testing as it is. The main reason why it has not been merged yet is because we are still working on getting schema evolution into this approach as well and we don't want to change the interface too often.

**Comment by tmadlener** [comment]
Closing, as this is no longer relevant with the removal of the `EventStore`
