### ISSUE TITLE
Enhancement: vectorized accessor to variable-length full array (constexpr)

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/podio#332]
In the vectorized access (notebook) pattern, we are currently required to pass the number of entries we wish to retrieve, as a constexpr on compile time, e.g. [`unittest.cpp`](https://github.com/AIDASoft/podio/blob/v00-15/tests/unittest.cpp#L186)
```cpp
  auto energies = hits.energy<10>();
```
With C++20, we have now compile-time access to `hits.size()` with [`constexpr size_type std::vector::size() const noexcept;`](https://en.cppreference.com/w/cpp/container/vector/size) (though not for `deque`, which is used for pointers and is what `hits.size()` actually uses) which would allow something like
```cpp
  auto energies = hits.energy<hits.size()>();
```
At this point, why not take the next step and implement a default `arraysize` in `template<{{ member.full_type }}, arraysize = m_storage.entries.size()>`, resulting in the following (also) working:
```cpp
  auto energies = hits.energy();
```
This interface would seem to allow for some clarity in downstream code that may be beneficial.

Before going too far into a rabbit hole of template code:
- Using a `deque` for the object pointers (instead of a `vector`) may be unavoidable, but we may be able to use `size()` on the `m_data` instead of the `entries` in `CollectionData.h`, or even implement a `constexpr size_type CollectionData::size() const;`.
- How do you feel about C++20 features that require special handling (we can't just `decltype` the return type of `std::vector::size()` since that doesn't include the `constexpr`-ness)? Does this lead to a jinja2 branch for `cxxstd==20` or something?
- Is all this worth it? Ultimately we're still running an AoS loop to get to the SoA representation...

**Comment by tmadlener** [comment]
I am not sure that `vector::size` being `constexpr` from c++20 really gains us anything in this case, since the inputs we are dealing with are (necessarily) not known at compile time. Hence, the size will also be unknown at compile time and it cannot be used as a template parameter. [See here](https://godbolt.org/z/9P4beKhG3) for a very simplified example of what I could get to work quickly in this context (and also some commented examples of things that do not work). Unless there are things that can be run at compile time without any runtime inputs, I don't think there is a lot of benefit of marking (parts) of the podio interfaces as `constexpr`. (This obviously doesn't mean that we cannot do it in any case).

On the other hand, I agree that the interface could be much more useful as it is at the moment, as having to specify *at compile time* how large our "vectors" shold be is a bit cumbersome. In that regard I think simply returning a `std::vector` instead of an `std::array` goes a rather long way. This would make the return value much more flexible, while still having the major characteristic of contiguous memory layout (albeit on the heap).

------
some comments / answers for your questions:
- Adding c++20 capabilities to the generated code could in principle be done with some pre-processor `#ifdefs` I think. The templates can be split into c++20 parts and others, so that at least that part could be kept maintainable I think. The generated code would obviously become somewhat harder to read, but I am not sure that is really a major concern.
- Regarding SoA vs AoS; I would say that the final word of how podio represents the data in memory is not yet spoken. Currently it is AoS, but nothing prevents us from switching to SoA here. The nice thing for the podio generated code is that we can in principle switch this out under the user interface transparently. This is at least something that I would definitely like to try, but this is something we can only start to do, once we have all the basic features in place.

**Comment by wdconinc** [comment]
> not known at compile time

It's not quite necessary that the *values are known* at compile time (which your example with random explicitly isn't), just that they can be *evaluated* at compile time. As far as I understand, essentially it is sufficient that at compile time the compiler knows exactly where to find the `size_t` value in order to be able to use it. So, `auto vecArrBySize = vectorized<vecArr.size()>()` is all we need in this particular case.

I also don't think it is necessary to make the collections themselves constexpr.

Regarding SoA vs AoS: I'd love a model where this can be decided at generation (or even at use). In one data model we may have collections (hits) that are going to benefit from SoA, but others that will be accessed in AoS (reconstructed particles). It would also be great if this ties into the data storage model, so we can squeeze those last performance percentage ;-)

**Comment by tmadlener** [comment]
I have to confess I miss quite a bit of the details that are involved here to really provide a knowledge backed answer, but my impression up until know was *can be evaluated at compile time* is more or less synonymous with *is known at compile time*, especially for template parameters. So I think simply knowing *where* to find a value is not enough to make it usable in a compile time (or constant evaluated) context, which would be necessary to declare `std::array` variables.

Anyhow, I think having a `std::vector` instead of an `std::array` doesn't really make a difference from the user perspective, other than that there is no need specify a size upfront for the `vector`.
