### ISSUE TITLE
Issue with clang format in the tests

### ISSUE THREAD

**Issue by jmcarcell** [AIDASoft/podio#388]
https://github.com/AIDASoft/podio/pull/358 introduced a sort of hidden dependency on `clang-format` as now there are tests which will generate a model with clang format and the `-fallback-style=llvm` argument is not supported by older versions of `clang-format`. This breaks the nightly build for key4hep, because `llvm` is not a dependency. I think we can agree that the tests should run without `llvm` since it's not a dependency of podio. These are some solutions I can think about:
- In the CMake step, when generating the original model save some variable to be checked later at the tests to make sure that we run the tests with the same arguments as now
- Alternatively we could just parse the dumped model and the original one even in a python one liner and compare the results. It's a slightly weaker test but there are tests already for the generation from the model

**Comment by tmadlener** [comment]
This could also be fixed by making the check for discovering `clang-format` more robust. Currently, it just checks for the presence, but does not try to actually run something:
https://github.com/AIDASoft/podio/blob/dc9b6bad7e5e3d499cfa900cbe74ea2aa4c85bab/python/podio_class_generator.py#L40-L49

Actually trying to run `clang-format` with all the flags we run it later should already fix all issues, because in case that does not succeed the generation will simply not format generated code.

We actually do something like that in the cmake macros:
https://github.com/AIDASoft/podio/blob/dc9b6bad7e5e3d499cfa900cbe74ea2aa4c85bab/cmake/podioMacros.cmake#L154

Overall, even that doesn't cover all possibilities yet, because the contents of `.clang-format` are in principle LLVM version dependent, and we require probably at least 9 or 10.
