### ISSUE TITLE
Improve python interface when adding collections to a frame

### ISSUE THREAD

**Issue by jmcarcell** [AIDASoft/podio#432]
At the moment writing collections and frames is possible from python but a bit cumbersome:
```python
from edm4hep import edm4hep
from ROOT import podio
from podio.root_io import Writer
import cppyy

writer = Writer('frame.root') # This will write the frame to a file called frame.root

frame = podio.Frame() # This is where the collection and other things will be stored
coll = edm4hep.MCParticleCollection() # Create an EDM4hep collection

coll.create() # Create a MutableMCParticle object

frame.put(cppyy.gbl.std.move(coll), "MCParticles") # Add collection to frame 

writer.writeFrame(frame, 'events')
writer.finish()

```
I think the agreement here is that `frame.put` should work without `cppyy.gbl.std.move` (and also with it in case someone is translating literally the C++ code?). I can give it a try this week, it should be easy to do

**Comment by tmadlener** [comment]
I am not entirely sure about whether it has to work both ways actually. I think having it work without `std.move` should be the main goal. In principle `std::move(std::move(foo))` should be valid c++, but I am not sure whether `cppyy` can handle it. Maybe it does and it just works out of the box. Otherwise we just document it.

Another interesting question to clarify is the state in which the collection is in after `put` (mainly for documentation purposes).

Related: #326
